name: "Dive CI"

on: [push]

jobs:
  dive:
    runs-on: ubuntu-latest
    name: Analyze image efficiency
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t iamsreelax/dive:v1 .
      - name: Dive
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: "iamsreelax/dive:v1"
      - name: push to docker hub
        run: |
          docker login -u iamsreelax -p DockerHub123
          # docker build -t iamsreelax/dive:2 
          docker push iamsreelax/dive:v1
      - uses: actions/upload-artifact@v1
        with:
         name: dive-test-results
         path: output/
         
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
         name: dive-results-html
         path: result.html
         
