name: dive tool
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu
    steps:
     - name: checkout repo
       uses: actions/checkout@v3
       with:
        ref: main
    #  - name: Login to DockerHub
    #    uses: docker/login-action@v2
    #    with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
   #  - name: Build and push
    #   #uses: docker/build-push-action@v2
    #   run: |
     #     docker login -u iamsreelax -p DockerHub123
      #    docker build -t iamsreelax/dive:26 .
       #   docker push iamsreelax/dive:26 
      #  with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #     push: true
      #     repo: iamsreelax/dive
      #     tags: iamsreelax/dive:25
     - name: Explore docker image
       timeout-minutes: 2
       env:
         CI: "true"
       run: |
         - apt install wget -y
         - wget https://github.com/wagoodman/dive/releases/download/v0.10.0/dive_0.10.0_linux_amd64.tar.gz
         - tar -xvzf dive_0.10.0_linux_amd64.tar.gz
         - ./dive iamsreelax/dive:26 
        #  ./dive $DOCKER_USERNAME/dive:$CI_PIPELINE_IID
   
