name: dive tool
on:
  push:
    branches:
      - 'main'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
         ref: main
    #  - name: Login to DockerHub
    #    uses: docker/login-action@v2
    #    with:
    #       username: ${{ secrets.DOCKERHUB_USERNAME }}
    #       password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
      #uses: docker/build-push-action@v2
        run: |
          docker login -u iamsreelax -p DockerHub123
          docker build -t iamsreelax/dive:27 .
          docker push iamsreelax/dive:27
          docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -e DOCKER_API_VERSION=1.37 wagoodman/dive:latest dive iamsreelax/dive:27
